version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: Etc/UTC

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: Etc/UTC
