name: justedlev-msrv
services:
  service-registry:
    container_name: service-registry
    image: justedlev/simple-eureka-server:latest
    build:
      context: .
    environment:
      spring_security_user_name: "{example}"
      spring_security_user_password: "{example}"
    ports:
      - "8761:8761"
    healthcheck:
      interval: 5s
      timeout: 3s
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health", "||", "exit 1" ]
