name: justedlev-msrv
services:
  service-registry:
    container_name: service-registry
    image: justedlev/simple-eureka-server:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8761:8761"
    healthcheck:
      interval: 5s
      timeout: 3s
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health", "||", "exit 1" ]
