name: justedlev-msrv
services:
  service-registry:
    container_name: ${SPRING_APPLICATION_NAME}
    image: justedlev/simple-eureka-server:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8761:${SERVER_PORT}"
    healthcheck:
      interval: 5s
      timeout: 3s
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health", "||", "exit 1" ]
    volumes:
      - ./logs:${LOGGING_FILE_PATH}
