name: justedlev-microservice
services:
  simple-eureka-server:
    container_name: simple-eureka-server
    image: justedlev/simple-eureka-server:1.0.0-SNAPSHOT
    build:
      context: .
    entrypoint:
      USERNAME: {example}
      PASSWORD: {example}
      SERVICE_DISCOVERY_ZONE: http://localhost:${server.port}/eureka
    ports:
      - 8761:8761
