name: justedlev-microservice
services:
  simple-eureka-server:
    build:
      context: .
    container_name: simple-eureka-server
    image: justedlev/simple-eureka-server:1.0.0-SNAPSHOT
    env_file:
      - docker.env
    ports:
      - 8761:8761
