name: justedlev-microservice
services:
  simple-eureka-server:
    container_name: simple-eureka-server
    image: justedlev/simple-eureka-server:1.0.0-SNAPSHOT
    build:
      context: .
    environment:
      USERNAME: "{example}"
      PASSWORD: "{example}"
    ports:
      - 8761:8761
