name: justedlev-msrv
services:
  service-registry:
    container_name: service-registry
    image: justedlev/simple-eureka-server:1.1.0
    build:
      context: .
    environment:
      spring_security_user_name: "{example}"
      spring_security_user_password: "{example}"
    ports:
      - "8761:8761"
