spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration
  cloud:
    bus:
      enabled: false
    config:
      enabled: false
management:
  server:
    port: -1
  endpoints:
    access:
      default: none
