management:
  server:
    port: 7761
  info:
    build:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
