server:
  port: 8761
  servlet:
    application-display-name: ${spring.application.name}
  error:
    include-message: always
spring:
  application:
    name: eureka
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KC_TOKEN_URI}
            issuer-uri: ${KC_ISSUER_URI}
            authorization-uri: ${KC_AUTH_URI}
            jwk-set-uri: ${KC_JWKS_URI}
            user-info-uri: ${KC_USER_INFO_URI}
            user-name-attribute: preferred_username
            user-info-authentication-method: header
        registration:
          eureka:
            provider: keycloak
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - discovery:rw
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}
          jwk-set-uri: ${KC_JWKS_URI}
        opaquetoken:
          introspection-uri: ${KC_INTROSPECTION_URI}
          client-id: ${KC_CLIENT_ID}
          client-secret: ${KC_CLIENT_SECRET}
eureka:
  instance:
    instance-id: ${spring.application.name}
    app-group-name: justedlev-msrv
    appname: ${spring.application.name}
    prefer-ip-address: true
    hostname: localhost
  client:
    restclient:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
management:
  server:
    port: 7761
  info:
    build:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
config-center:
  security:
    whitelist:
      GET:
        - /webjars/**
        - /v3/api-docs/**
        - /swagger-ui.html
        - /swagger-ui/**
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /actuator/health
        - /error
      POST:
        - /sso/logout
        - /logout
