server:
  port: 8761
  servlet:
    application-display-name: ${spring.application.name}
spring:
  application:
    name: '@project.name@'
  config:
    import:
      - classpath:/eureka.yml
      - classpath:/logging.yml
      - classpath:/security.yml
      - classpath:/management.yml
