server:
  port: 8761
  servlet:
    application-display-name: ${spring.application.name}
  error:
    include-message: always
spring:
  application:
    name: '@project.name@'
  cloud:
    config:
      enabled: false
  config:
    import:
      - 'optional:configserver:'
      - classpath:/eureka.yml
      - classpath:/logging.yml
      - classpath:/security.yml
      - classpath:/management.yml
