spring:
  security:
    user:
      name: ${USERNAME:eureka}
      password: ${PASSWORD}
      roles: ${ROLES:system}
security:
  whitelist:
    - /webjars/**
    - /v3/api-docs/**
    - /*/v3/api-docs/**
    - /*/*/v3/api-docs/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /swagger-resources
    - /swagger-resources/**
    - /configuration/ui
    - /configuration/security
    - /actuator/**
    - /*/actuator/**
    - /error
    - /logout
