spring:
  security:
    user:
      name: ${USERNAME:eureka}
      password: ${PASSWORD:}
      roles: ${ROLES:system}
security:
  whitelist:
    GET:
      - /webjars/**
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /*/*/v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/ui
      - /configuration/security
      - /actuator/**
      - /*/actuator/**
      - /error
    POST:
      - /sso/logout
      - /logout
