name: justedlev-msrv
services:
  api-gateway.justedlev.io:
    tty: true
    env_file:
      - .env
    container_name: ${SPRING_APPLICATION_NAME}
    image: justedlev/simple-eureka-server:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512MB
